"use strict";
Math.round(3.14);
const myVar = 54;
let MovieTitle = "Mahan";
MovieTitle = 54;
MovieTitle.toUpperCase();
let catNums = 9;
catNums += 1;
let gameOver = false;
gameOver = true;
gameOver = "true";
